excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://elliottroland.github.io
title: Thought combinator
tagline: Optimistically attempting to drive out kipple
description: Thoughts on system design, software engineering, best practices, formalisms, and things like these
paginate: 50
